name: "Podcast Gene"
author: "Brandon Looker"
description: "Generate a feed for a podcast from a YAML file"
runs:
  using: "docker"
  image: "Dockerfile"
branding:
  icon: "git-branch"
  color: "red"
iputs:
  email:
    description: The commiter's email address
    required: true
  name: 
    description: The commiter's name
    required: true
